### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by teocomi** [CircleCI-Public/aws-s3-orb#19]
**Is your feature request related to a problem? Please describe.**
Add suppport for windows environments.

I might be missing something, but it seems that this orb doesn't work on windows. Could you please add support or provide a workarond in the orb description?

Thanks

```
bash: line 37: sudo: command not found
```

**Comment by brivu** [comment]
Hey @teocomi, 

I've added additional testing to this orb using the windows executor. Make sure you specify `bash.exe.` as your `shell`.

Here's an example from our config: 

```
executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
    shell: bash.exe
    resource_class: windows.medium
jobs:
  integration-test:
    parameters:
      executor:
        type: executor
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: "s3://orb-testing-1/s3-orb"
          role-arn: arn:aws:iam::122211685980:role/CPE_S3_OIDC_TEST
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: "s3://orb-testing-1"
          role-arn: arn:aws:iam::122211685980:role/CPE_S3_OIDC_TEST
          install-aws-cli: false
workflows:
  test-deploy:
    jobs:
      - integration-test:
          name: integration-test
          context: [CPE-OIDC]
          filters: *filters
          executor: "windows"
```
