### ISSUE TITLE
AWS-S3 orb not working, "aws: command not found"

### ISSUE THREAD

**Issue by mckernanin** [CircleCI-Public/aws-s3-orb#4]
### Orb version

circleci/aws-s3@1.0.15

### What happened
![Screenshot 2020-02-04 15 00 34](https://user-images.githubusercontent.com/6300047/73791212-1cde0900-475f-11ea-8003-bb6f4a02830d.png)

### Expected behavior

AWS CLI should be setup properly.
Relevant config pieces from config.yml:

```yaml
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
s3config: &s3config
  aws-access-key-id: AWS_ACCESS_KEY_ID
  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  aws-region: AWS_REGION
  arguments: |
    --acl public-read \
    --cache-control "max-age=86400"
  overwrite: true

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk

jobs:
  deploy-prod:
    executor: gcloud
    steps:
      - checkout
      - run: bash ./scripts/auth-gcp.sh
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run: bash ./scripts/deploy-prod.sh
      - aws-s3/sync:
          <<: *s3config
          from: workspace/build/static/js
          to: 's3://path/app/static/js'
      - aws-s3/sync:
          <<: *s3config
          from: workspace/build/static/css
          to: 's3://path/app/static/css'
      - aws-s3/sync:
          <<: *s3config
          from: workspace/build/static/media
          to: 's3://path/app/static/media'
```
