### ISSUE TITLE
aws command not found orb 3.1.1

### ISSUE THREAD

**Issue by rodolfoIOET** [CircleCI-Public/aws-s3-orb#44]
**Orb version**
3.1.1

**Describe the bug**
I'm getting "/bin/bash: line 14: aws: command not found" when using "aws-s3/sync"

**To Reproduce**

my_job:
    docker:
      - image: cimg/node:lts-browsers
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=86400"
          from: screenshots
          to: 's3://my_s3_bucket/yyyy'
          when: on_fail

**Expected behavior**

successfully set up aws-cli, because "install-aws-cli" param is default to true

**Additional context**
I think this is because the Shebang used in the orb source: #!/bin/sh
and this might be related https://github.com/CircleCI-Public/aws-s3-orb/issues/4

**Comment by kelvintaywl** [comment]
Hi @rodolfoIOET 

would your project on CircleCI be a private repository?
If so, can you submit a support ticket here @ https://circleci.zendesk.com/hc/en-us/requests/new ?
From there, we (Support team) can dig deeper and look at your CircleCI build to advise further.

Thank you!

**Comment by qops1981** [comment]
I am running into the same thing. For me! it looks like when you pass the `when:` parameter in IT IS NOT passing to the "Install AWS CLI - latest" AND "Configure AWS Access Key ID" steps. These steps are notably missing when the step before fails.

```yaml
      - run:
          name: "Check the pre-existence of the deploy"
          command: |
            echo "${DEPLOY_PATH}"
            sideshow staging is_deployed ${DEPLOY_PATH}
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - backup_deploy:
                bucket: staging
                current: "${DEPLOY_PATH}"
                when: on_success
      - aws-s3/copy:
          arguments: |
            --cache-control "public, max-age=15" \
            --acl bucket-owner-full-control
          from: build/code-snippet.js # build/${FILENAME}
          to: "s3://staging/sideshow/${DEPLOY_PATH}"
          when: always
```

![image](https://user-images.githubusercontent.com/7356650/217647971-bf699194-7009-422d-91ba-e0cc662b05e4.png)
