### ISSUE TITLE
about arguments in aws s3 sync

### ISSUE THREAD

**Issue by JooeunAhn** [CircleCI-Public/aws-s3-orb#56]
**Orb Version**
`aws-s3: circleci/aws-s3@4.0`

**Describe the bug**

In orb version 4.0, I tried to ignore hidden files when aws sync.
to do that I tried to use like this
```
      - aws-s3/sync:
          arguments: --delete --exclude '.*'
          from: ./
          to: {target}
```
but ci runs like that and then it failed to ignore hidden files...
```
aws s3 sync ./ s3://web-docs-apne1-stg/CINF-2620-test/ --profile default --delete --exclude ''\''.*'\'''
```

is there any way to do that without escaping? thanks!
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by kzk-maeda** [comment]
I've encountered the similar issue.
In my case, I've written circle ci configuration like this:

```yaml
      - aws-s3/sync:
          arguments: |
            --cache-control "public,max-age=31536000,immutable" \
            --exclude "index.html"
          from: dist
          to: << parameters.s3_url >>
```

Then, the job failed as below:

```
aws s3 sync dist s3://bucket/path --cache-control '"public,max-age=31536000,immutable"' '\
--exclude' '"index.html"'

Unknown options: \
--exclude,"index.html"

Exited with code exit status 252
```
