### ISSUE TITLE
Missing parameter auth in command aws-s3/sync

### ISSUE THREAD

**Issue by juanariastn** [CircleCI-Public/aws-s3-orb#58]
**Orb Version**
`circleci/aws-s3@4.0.0`

**Describe the bug**
Hi! Thanks for the work in this ORB 🙏 

I'm trying to use the command `aws-s3/sync` with `auth` parameter, to use OIDC authentication. 
And I see this error in both CircleCI cli and in the pipeline.

```
$ circleci config validate
Error: config compilation contains errors: config compilation contains errors:
	- Error calling workflow: 'staging-test-and-deploy'
	- Error calling job: 's3-sync'
	- Error calling command: 'aws-s3/sync'
	- Unexpected argument(s): auth
```

**To Reproduce**

Fragment of my CircleCI config:
```yml
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.1.0
  aws-s3: circleci/aws-s3@4.0.0
  
jobs:
  s3-sync:
    docker:
      - image: 'cimg/python:3.6'
    parameters:
      aws_region:
        type: env_var_name
      bucket_name:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - aws-s3/sync:
          auth:
            - aws-cli/setup:
                role_arn: ...
                region: ...
          from: public/
          to: 's3://<< parameters.bucket_name >>'

workflows:
  staging-test-and-deploy:
    ...
    - s3-sync:
          name: stg-s3-sync
          context: ...
          aws_region: ...
          bucket_name: ...
          filters:
            <<: *filter-staging
```

**Expected behavior**
The command should accept the argument `auth`, just like `aws-s3/sync` job

**Additional context**
<img width="1474" alt="Screenshot 2024-09-30 at 14 54 17" src="https://github.com/user-attachments/assets/1f6fd44e-aacb-4c7e-b914-ac3c69c41bfc">
<img width="1474" alt="Screenshot 2024-09-30 at 14 54 56" src="https://github.com/user-attachments/assets/1b64180b-dc93-4b73-8da9-76ed2eaa2bd9">
