### ISSUE TITLE
Unable to interpolate bash functions

### ISSUE THREAD

**Issue by MrSwitch** [CircleCI-Public/aws-s3-orb#60]
**Orb Version**
4.1.0

**Describe the bug**
Unable to process bash functions within the text. In the code below the short sha1 bash substring function `${CIRCLE_SHA1:0:7}` is not interpolated. Instead the whole `CIRCLE_SHA1` value is returned. Effectively been regarded as `${CIRCLE_SHA1}`

note: This worked in version 2.0.0 and only since upgrading did this break.

**To Reproduce**

```yml
jobs:
   push_to_s3:
       steps:
            - aws-s3/sync:
                  from: dist
                  to: s3://bucket/path/${CIRCLE_SHA1:0:7}

```

Or (and i find this a bit strange) defined as a parameter the effects are also the same...

```yml
jobs:
   push_to_s3:
      parameters:
           short_sha1: 
                type: string
       steps:
            - aws-s3/sync:
                  from: dist
                  to: s3://bucket/path/<< parameter.short_sha1 >>

workflow:
    build:
       jobs: 
          - push_to_s3:
                short_sha1: ${CIRCLE_SHA1:0:7}

```

**Expected behavior**
When `CIRCLE_SHA1=6226af44a63e23bbc743cfb44c339c532e85dc2e`

`${CIRCLE_SHA1:0:7}` should trimmed to 7 characters, i.e. `6226af4`

But instead `${CIRCLE_SHA1:0:7}` returns `6226af44a63e23bbc743cfb44c339c532e85dc2e` ???
