### ISSUE TITLE
I want to override the default command names

### ISSUE THREAD

**Issue by seanssel** [CircleCI-Public/aws-s3-orb#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The commands have step names hardcoded, like "S3 Sync" for `aws-s3/sync`. I want to be able to customize this name so that I can have more immediate context when viewing steps on the dashboard.

```yaml
jobs:
  some-job:
    steps:
      - aws-s3/sync:
          name: "My custom name"
          ...
```

**Additional context**
N/A
